DROP TABLE IF EXISTS scores;
CREATE TABLE scores (pid TEXT NOT NULL, name TEXT NOT NULL, n INTEGER NOT NULL, t INTEGER NOT NULL);
CREATE INDEX scores_pid ON scores (pid, n DESC);
CREATE TABLE IF NOT EXISTS tokens (tok TEXT PRIMARY KEY, pid TEXT NOT NULL, ip TEXT NOT NULL, t0 INTEGER NOT NULL, used INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS tokens_ip ON tokens (ip, t0);
